### ISSUE TITLE
安装后启动失败

### ISSUE THREAD

**Issue by LancelotLewis** [blocklet/nft-lottery-demo#4]
https://github.com/ArcBlock/blocklet-server/issues/3990
![image](https://user-images.githubusercontent.com/8749615/150510977-10360476-312d-4502-b269-9c90ba56da52.png)

**Comment by LancelotLewis** [comment]
![image](https://user-images.githubusercontent.com/8749615/150512358-03f44fd9-7b5c-49cb-9639-60a7831138be.png)

---
Start blocklet nft-lottery-demo failed with error: Run [pre-start] failed: /Users/han/workspace/an-test/2022-01-21/.abtnode/blocklets/nft-lottery-demo/1.0.3/node_modules/@ocap/asset/lib/index.js:122 throw new Error('Factory hooks should not be empty for instant settlement'); ^ Error: Factory hooks should not be empty for instant settlement at isValidFactory (/Users/han/workspace/an-test/2022-01-21/.abtnode/blocklets/nft-lottery-demo/1.0.3/node_modules/@ocap/asset/lib/index.js:122:13) at getFactoryProps (/Users/han/workspace/an-test/2022-01-21/.abtnode/blocklets/nft-lottery-demo/1.0.3/server/libs/nft.js:81:3) at /Users/han/workspace/an-test/2022-01-21/.abtnode/blocklets/nft-lottery-demo/1.0.3/server/libs/factory.js:37:5 at Array.map (<anonymous>) at Object.<anonymous> (/Users/han/workspace/an-test/2022-01-21/.abtnode/blocklets/nft-lottery-demo/1.0.3/server/libs/factory.js:34:31) at Module._compile (node:internal/modules/cjs/loader:1101:14) at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10) at Module.load (node:internal/modules/cjs/loader:981:32) at Function.Module._load (node:internal/modules/cjs/loader:822:12) at Module.require (node:internal/modules/cjs/loader:1005:19)
---
